### ISSUE TITLE
 Cannot Compile

### ISSUE THREAD

**Issue by sahilshekhawat** [mauromoura/opendaylight-firewall#2]
[ERROR]     Non-resolvable parent POM: Could not find artifact org.opendaylight.odlparent:odlparent:pom:1.6.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 10, column 11 -> [Help 2]

**Comment by mauromoura** [comment]
Hi! Did you configure your maven settings.xml to access opendaylight artifacts repository? 
[opendaylight maven configuration](https://wiki.opendaylight.org/view/GettingStarted:Development_Environment_Setup#Edit_your_.7E.2F.m2.2Fsettings.xml)
